# Generated by Django 3.2.3 on 2022-02-12 03:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(240), django.core.validators.MinValueValidator(100)])),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=10, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('physical_activity', models.CharField(blank=True, choices=[('1.2', 'Baja'), ('1.375', 'Ligera'), ('1.55', 'Moderada'), ('1.725', 'Intensa')], max_length=5, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutricionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imc', models.IntegerField(blank=True, null=True)),
                ('calories_day', models.IntegerField(blank=True, null=True)),
                ('weight_status', models.CharField(blank=True, choices=[('1', 'Low weight'), ('2', 'Normal weight'), ('3', 'Overweight'), ('4', 'Obesity')], max_length=20, null=True)),
                ('meals_cant', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
